title: Max Julius Hilgenberg's<br>Homepage
description: <br><em><b>To think is easy. To act is hard. But the hardest thing in the world is to act in accordance with your thinking.</em></b><br> - Johann Wolfgang von Göthe
logo: /images/mhilgen_frame.png
show_downloads: true
theme: jekyll-theme-minimal
