title: Max J. Hilgenberg's Home
description: <br><em>To think is easy. To act is hard. But the hardest thing in the world is to act in accordance with your thinking.</em><br> - Johann Wolfgang von Göthe
logo: /images/mhilgen_frame.png
show_downloads: true
theme: jekyll-theme-minimal
