title: Max J. Hilgenberg's Home
description: To think it is easy. Do act is hard. But the hardest thing in the world is to act in accordance with your thinking - Johann Wolfgang von Göthe
logo: /images/mhilgen_frame.png
show_downloads: true
theme: jekyll-theme-minimal
